mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import debug_toolbar

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

news/urls.py
from django.urls import path
from news import views

app_name = 'news'
urlpatterns = [
    # path('', views.index, name='home'),
    path('', views.HomeNews.as_view(), name='home'),
    # path('category/<slug:category_slug>', views.get_category, name='category'),
    path('category/<slug:category_slug>', views.NewsByCategory.as_view(), name='category'),
    # path('news/<slug:news_slug>', views.view_news, name='view_news'),
    path('news/<slug:news_slug>', views.ViewNews.as_view(), name='view_news'),
    # path('news/add-news/', views.add_news, name='add_news'),
    path('news/add-news/', views.CreateNews.as_view(), name='add_news'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

templates/layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'news:home' %}">Home</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'news:add_news' %}">Add news</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>

    <span class="navbar-text">
      {% if request.user.is_authenticated %}
        Hello {{ user.username }} | <a href="{% url 'news:logout' %}">Logout</a>
      {% else %}
        <a href="{% url 'news:register' %}">Register</a> | <a href="{% url 'news:login' %}">Login</a>
      {% endif %}
    </span>
  </div>
</nav>

templates/layout/sidebar.html
{% load news_tags %}

{% show_categories curCategory.id %}